version: "3.8"

services:
  # Service cho MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - agent-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Service cho API
  api:
    build:
      context: .
    container_name: agent-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - agent-network
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  agent-network:
    driver: bridge
