agent_id: 5e02b315-c808-450c-8205-de88e30edae1
name: Multi Agent
type: multi
sub_agents:
- agent_id: c9e381c7-4115-4f8a-a733-43be10a72768m
  name: Goal Agent
  description: Agent tìm kiếm thông tin về mục tiêu và các đợt đánh gia KPI của công
    ty, nhân viên, bộ phận
  type: fc
  nodes:
    llm:
      provider: openai
      agent_prompt: ''
    tools:
    - type: store
      name: get_goal
      description: Lấy danh sách mục tiêu hoặc KPI của bộ phận
      tool_path: ''
      input_params:
      - name: Representative
        description: Tên người đại diện của bộ phận
        input_method: query
        type: string
        default: ''
        required: false
      - name: GoalName
        description: Tên mục tiêu KPI
        input_method: query
        type: string
        default: ''
        required: false
      method: GET
      store_name: sp_eva_get_goal_department
      tool_type: dynamic
    - type: store
      name: get_evaluation_period
      description: Lấy danh sách các đợt đánh giá
      tool_path: ''
      input_params:
      - name: Name
        description: Tên đợt đánh giá
        input_method: query
        type: string
        default: ''
        required: false
      method: GET
      store_name: sp_get_cat_evaluation_period
      tool_type: dynamic
    - type: store
      name: get_goal_personal
      description: Lấy danh sách mục tiêu hoặc KPI chi tiết của cá nhân
      tool_path: ''
      input_params:
      - name: AssignedToProfileId
        description: ID nhân viên
        input_method: query
        type: string
        default: c895f92b-4745-49f8-99a8-8b261294e659
        required: true
      - name: PeriodId
        description: Kỳ mục tiêu
        input_method: query
        type: string
        default: adcb9920-0078-43fe-a02a-e78cc488b87d
        required: true
      method: GET
      store_name: sp_eva_get_goal_personal_detail
      tool_type: dynamic
    - type: store
      name: get_eva_evaluation_person
      description: Lấy phiếu đánh giá của nhân viên
      tool_path: ''
      input_params: []
      method: GET
      store_name: sp_get_eva_evaluation_person
      tool_type: dynamic
    - type: store
      name: get_progress_overview
      description: Lấy danh sách tiến độ mục tiêu
      tool_path: sp_eva_get_progress_overview
      input_params: []
      method: GET
      store_name: sp_eva_get_progress_overview
      tool_type: dynamic
    - type: built_in
      name: register_goal
      description: Thực hiện giao mục tiêu cho phòng ban bộ phận
- agent_id: f73bdfc06c6f2e9741826c1ce81a982b
  name: Training Agent
  description: Agent tìm kiếm thông tin về việc đào tạo, khóa học, tài liệu, bài giảng
    và tài liệu hướng dẫn sử dụng hệ thống elearning
  type: fc
  nodes:
    llm:
      provider: openai
      agent_prompt: ''
    tools:
    - type: built_in
      name: get_courses
      description: Lấy danh sách khóa học
    - type: built_in
      name: get_documents
      description: Lấy tài liệu trong khóa học, bài giảng ..
    - type: built_in
      name: get_hdsd
      description: Lấy tài liệu hướng dẫn sử dụng hệ thống
auth:
  method: oauth2
  url_endpoint: https://qc-core.vnrlocal.com:3019/
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjZBNEIxNERDQzEzMjFGQzMzMDM3QUU5QUYyNDQzRjkyIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3NTQ0NzU2NzksImV4cCI6MTc1NDQ3OTI3OSwiaXNzIjoiaHR0cHM6Ly9xYy1jb3JlLnZucmxvY2FsLmNvbTozMDA1IiwiYXVkIjpbInByb2ZpbGUiLCJodHRwczovL3FjLWNvcmUudm5ybG9jYWwuY29tOjMwMDUvcmVzb3VyY2VzIl0sImNsaWVudF9pZCI6IjgwZGRlM2NiYWVkMzRlMDliNDdmMTIxNzI2Y2Y3ZTI1Iiwic3ViIjoiMGJkNTM1M2UtOTMyNS00OGZlLTgwOTEtMDMzYzgxYjQ2ZDNjIiwiYXV0aF90aW1lIjoxNzU0NDc1Njc5LCJpZHAiOiJsb2NhbCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ2bnIiLCJocm1fdXNlcl9pZCI6IjBiZDUzNTNlLTkzMjUtNDhmZS04MDkxLTAzM2M4MWI0NmQzYyIsImhybV9wcm9maWxlX2lkIjoiNDgwMTBjZTUtODhlZS00ZjZlLWFiNjQtNzhiYzJlYmRlMjcxIiwiaHJtX3VzZXJuYW1lIjoidm5yIiwiaHJtX2lzX2FjdGl2YXRlIjoidHJ1ZSIsImhybV90eXBlX3VzZXIiOiJFX01haW4sRV9Qb3J0YWwiLCJocm1fZnVsbG5hbWUiOiJMw6ogxJDDoG8iLCJocm1fdXNlcl9pbmZvX25hbWUiOiJMw6ogxJDDoG8iLCJocm1fY29kZV9lbXAiOiJWUDAyOTc1IiwiaHJtX2ltYWdlX3BhdGgiOiJQcm9maWxlX2FmMTUxZGU1LTkyMDctNDUyNC1iY2E5LTdkOTBkNGE1MzBjNS5wbmciLCJocm1fZW1haWwiOiJ0ZXN0ZGFuZ2t5dm5yZXNvdXJjZUBnbWFpbC5jb20iLCJocm1faXNfc3VwZXJfYWRtaW4iOiJ0cnVlIiwiaHJtX2xhbmdfY29kZSI6IlZOIiwianRpIjoiNEFGOTNDQTY1NkFCNEUwOTZERkUxQ0JCMjUxMDVDMEYiLCJpYXQiOjE3NTQ0NzU2NzksInNjb3BlIjpbImFwaSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwYXNzd29yZCJdfQ.gH7LSDpgsULsWz9BN_yHSyoG5oeTHT5RQJYcRPQW9JJg31DmGJ_p1cEAeFy8tvAmZUmplEO6AvAbkoKrM7lBKdlmW9jaXqLfFXI69yUpG0mGd8bboIXrrhm4Eo0tAz6eW-5M3iJ7Nvv8Gvf3-9FYl4cMrLyOcvMnSmbRVd1Qsaj_znkp9lPqqoip2dvtg7XZ4ClrVDKl-XiiK4ow-lwuyl4BhPVxFXzlKQDp8MAeGyAR0oOGJlKfkA1mJHSVJTElmoEkHDGCQ6jNVrg3B5J2RQ5RrUXpChxWQyty3gohLxBShZsLgJ3lbulWDLPHFT9WV0VA1-lXnHtumv7WdZDORw
